### ISSUE TITLE
Option to use getaddress.io API

### ISSUE THREAD

**Issue by Jamesking56** [JustSteveKing/LaravelPostcodes#38]
Thanks for the great package!

It would be nice if we could instead use the API from https://getaddress.io since that API can turn postcodes into full addresses.

**Comment by JustSteveKing** [comment]
Hey @Jamesking56 thanks for the idea!

It's not quite the intended use of this library, this library is more for validation of UK postcodes than full address fetching. Definitely something I will think on!

Do you have any idea how you'd imagine this working at all?

**Comment by Jamesking56** [comment]
Well I'm currently looking at integrating getaddress.io into an app and might turn it into a package and open source it. I then noticed your package here and wondered if it could support multiple APIs

**Comment by JustSteveKing** [comment]
I think changing the intention of this package, to suit 2 APIs would introduce a few too many breaking changes. While I agree it would be a good feature to add, it would also be a lot of refactoring for something I don't use (getAddress.io)

I would highly recommend if it is something you _need_ that you build it yourself.

If you want a quick option to build this out as a package: https://github.com/SuitcasePHP/builder is something I built awhile ago which is a simplistic way to build API wrapper libraries 😄 

Otherwise, I am actually building a more integrated way to build PHP SDKs - which I expect to be published in the next few weeks.
